### ISSUE TITLE
CRIU-Image-Streamer working

### ISSUE THREAD

**Issue by shubham95** [checkpoint-restore/criu-image-streamer#1]
how it works
Like dump and restore starts parallel and files are transferred on the fly

![WhatsApp Image 2020-06-05 at 9 52 29 AM](https://user-images.githubusercontent.com/5495227/83836968-c388e500-a712-11ea-88c4-2d5c4dfe970b.jpeg)
Otherwise How it is different from CRIU page server

**Comment by nviennot** [comment]
The streamer can do live migrations, but doesn't need to.

Think that the streamer is just an extension to make CRIU think that the image is not a bunch of files on disk, but rather a UNIX pipe. With that in mind, you can think of being able to do conceptually:

1) `criu dump | lz4 > image.lz4` then `cat image.lz4 | lz4 -d | criu restore`
2) `criu dump | ssh | criu restore`

The CRIU page server is specifically solving the problem of live migration with keeping the downtime of the application minimal.
The streamer does not care how long the application is going to be down for. Rather, it tries to do the checkpoint as fast as it can in one go.

**Comment by shubham95** [comment]
@nviennot  How its optimizes checkpoint time?
