### ISSUE TITLE
Error of broken pipe 

### ISSUE THREAD

**Issue by shubham95** [checkpoint-restore/criu-image-streamer#2]
criu :  Version: 3.14
GitID: v3.14-113-g11eb590b

kernel : 4.15.0-99-generic

sudo criu dump --images-dir tmp --remote --shell-job -t 31837
Error (criu/img-remote.c:174): Unable to connect to local socket: img-proxy.sock: Connection refused
Error (criu/image.c:492): Unable to open pagemap-31837.img: Connection refused
Error (criu/mem.c:644): Can't dump page with parasite
Error (criu/bfd.c:132): bfd: Error flushing image: Broken pipe
Error (criu/bfd.c:132): bfd: Error flushing image: Broken pipe
Error (criu/bfd.c:132): bfd: Error flushing image: Broken pipe
Error (criu/bfd.c:132): bfd: Error flushing image: Broken pipe
Error (criu/img-remote.c:174): Unable to connect to local socket: img-proxy.sock: Connection refused
Error (criu/img-remote.c:1058): Unable to open finish dump connectionError (criu/cr-dump.c:1770): Finish remote dump failed.

sudo ./criu-image-streamer/criu-image-streamer --images-dir project/tmp/ capture | lz4 -f project/tmp/img.lz4 
Decoding file project/tmp/img 
Unable to access file for processing: project/tmp/img.lz4
socket-init
checkpoint-start
Error: Failed to write protobuf

Caused by:
    Broken pipe (os error 32)

**Comment by nviennot** [comment]
Copy/pasting Example 1 in the documentation should just work.
What do you get?

**Comment by shubham95** [comment]
Yeah It worked turned out that i didn't used sudo for criu-image-streamer
