### ISSUE TITLE
How is this image streamer diffrent/better than CRIU page-Server

### ISSUE THREAD

**Issue by DallelKh** [checkpoint-restore/criu-image-streamer#6]

**Comment by rst0git** [comment]
Hi @DallelKh, this is a good question.

#### Short answer
- [Page server](https://criu.org/Page_server) handles only memory pages
- Image streamer transfers all [image files](https://criu.org/Images)

#### Long answer
CRIU is using a [protocol buffer](https://developers.google.com/protocol-buffers/) format to encode serialized data representation of a process tree (checkpoint). This data (by default) is stored as [image files](https://criu.org/Images), where each file contains information such as open file descriptors, memory pages, sockets, etc. In most cases, memory pages are the largest component of a checkpoint, and in the context of live migration it takes significant amount of time to be migrated to a destination host.

The page server was introduced to enable the transfer of memory pages directly from source to destination host and it can be used for [pre-copy](https://criu.org/Iterative_migration) and [post-copy](https://criu.org/Lazy_migration) migration. However, all other images are stored as files in the path provided with `--images-dir`.

The image streamer replaced a prototype of the [--remote](https://criu.org/CLI/opt/--remote) option in CRIU. It allows to transfer all images (not only memory pages) directly from source to destination host.

I hope this answers your question.

**Comment by nviennot** [comment]
Another precision: criu-image-streamer emits the image on UNIX pipes, not just TCP. That means that you can do compression, encryption, and upload to a location of your choice (e.g., AWS S3) by plugging UNIX commands in. That's something the page server does not do.
